# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Shrimpwr\Desktop\Study\softwaredev_course_design\source\UI\book_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_book_page(object):
    def setupUi(self, book_page):
        book_page.setObjectName("book_page")
        book_page.resize(669, 545)

        self.retranslateUi(book_page)
        QtCore.QMetaObject.connectSlotsByName(book_page)

    def retranslateUi(self, book_page):
        _translate = QtCore.QCoreApplication.translate
        book_page.setWindowTitle(_translate("book_page", "Form"))
