# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Shrimpwr\Desktop\Study\softwaredev_course_design\source\UI\book_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_book_page(object):
    def setupUi(self, book_page):
        book_page.setObjectName("book_page")
        book_page.resize(1179, 841)
        self.tableWidget = QtWidgets.QTableWidget(book_page)
        self.tableWidget.setGeometry(QtCore.QRect(0, 30, 911, 811))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.tableWidget.setFont(font)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.label = QtWidgets.QLabel(book_page)
        self.label.setGeometry(QtCore.QRect(0, 0, 101, 31))
        self.label.setTextFormat(QtCore.Qt.PlainText)
        self.label.setObjectName("label")

        self.retranslateUi(book_page)
        QtCore.QMetaObject.connectSlotsByName(book_page)

    def retranslateUi(self, book_page):
        _translate = QtCore.QCoreApplication.translate
        book_page.setWindowTitle(_translate("book_page", "Form"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("book_page", "新建行"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("book_page", "Cover"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("book_page", "Title"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("book_page", "Authors"))
        self.label.setText(_translate("book_page", "TextLabel"))
