# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Shrimpwr\Desktop\Study\softwaredev_course_design\source\UI\search_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_search_page(object):
    def setupUi(self, search_page):
        search_page.setObjectName("search_page")
        search_page.resize(672, 548)
        self.pushButton = QtWidgets.QPushButton(search_page)
        self.pushButton.setGeometry(QtCore.QRect(270, 310, 111, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.pushButton.setFont(font)
        self.pushButton.setAutoDefault(False)
        self.pushButton.setDefault(False)
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(search_page)
        self.lineEdit.setGeometry(QtCore.QRect(60, 180, 541, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.lineEdit.setFont(font)
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")

        self.retranslateUi(search_page)
        QtCore.QMetaObject.connectSlotsByName(search_page)

    def retranslateUi(self, search_page):
        _translate = QtCore.QCoreApplication.translate
        search_page.setWindowTitle(_translate("search_page", "Form"))
        self.pushButton.setText(_translate("search_page", "搜索"))
